#!/bin/bash
#gunicorn -c /home/flcadmin/fred.flchomegroup.com/gunicorn_config.py bob.wsgi

NAME="bob"                                  # Name of the application
DJANGODIR=/webapps/fred.flchomegroup.com/bob            # Django project directory
SOCKFILE=//webapps/fred.flchomegroup.com/run/gunicorn.sock
USER=fred
GROUP=webapps
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=bob.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=bob.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-file=-
